### PR TITLE
Added regex that works with default NeoMutt alias_format

### PR DESCRIPTION
**Pull request by hvanderheide**
I didn't dig too deep into this but the default muttalias script didn't
work with my NeoMutt config. When NeoMutt writes to the alias file it
uses the following (default) format:
alias_format="%4n %2f %t %-10a   %r"

My simple regex isn't as sophisticated as the other ones since I didn't fully understand what they were doing. Any feedback is very welcome

### CODE REVIEW

**Comment by RolandRosenfeld** [comment]
I do not fully understand, what goes wrong on your side.
alias_format only defines how aliases are displayed inside mutt, this hasn't any influence on the format of the aliases file.
Can you give an example alias line from your alias file, that isn't catched by the current RegEx. Usually the aliases should be something like
alias roland1 Roland Rosenfeld <roland@spinnaker.de>
alias roland2 roland@spinnaker.de (Roland Rosenfeld)
And some variants of this (including groups etc., that are not handled by m_muttalias.
So what format do you use, that isn't catched by m_muttalias?

**Comment by hvanderheide** [comment]
Hi, thanks for the quick reply. My aliases look like:
alias test_alias Test 123 <text@example.com>

I don't think my current configuration changes the default way NeoMutt creates the aliases.

**Comment by RolandRosenfeld** [comment]
You are talking about the create-alias function in mutt, aren't you?

**Comment by hvanderheide** [comment]
Correct. I should probably note that I'm on a Mac with an ancient version of sed. I havn't tried with a more modern version yet.

**Comment by RolandRosenfeld** [comment]
That sounds bad. I thought that sed is somewhat portable, at least the version used in OS-X, which should be GNU or BSD...
If you could find out what version of sed this is and what's going wrong here, let me know, maybe I have a chance to work around this incompatibility, require some other version of sed or rewrite the tool to work with your version of sed, too...

**Comment by hvanderheide** [comment]
I can't find a version but the binary has some clues:

$ strings /usr/bin/sed
$FreeBSD: src/usr.bin/sed/compile.c,v 1.28 2005/08/04 10:05:11 dds Exp $
$FreeBSD: src/usr.bin/sed/main.c,v 1.36 2005/05/10 13:40:50 glebius Exp $
$FreeBSD: src/usr.bin/sed/misc.c,v 1.10 2004/08/09 15:29:41 dds Exp $
$FreeBSD: src/usr.bin/sed/process.c,v 1.39 2005/04/09 14:31:41 stefanf Exp $
@(#)PROGRAM:sed  PROJECT:text_cmds-97

**Comment by hvanderheide** [comment]
I just compiled sed 4.4 for my Mac and this fixed my issue. So I guess this pull request turns more into an issue than a change

**Comment by RolandRosenfeld** [comment]
I just tried this out on a FreeBSD myself and you are right, this is a sed incompatibility in m_muttalias, which I introduced in https://github.com/RolandRosenfeld/lbdb/commit/e4f7a726cb496736e4c8939c97b3069af355b6ee
I think that I won't apply your patch but try to rewrite the above commit to become compatible with FreeBSD sed.

This may take some time, since I'm just writing a test suite for lbdb, where this will be one of the first tests, which I then can run on FreeBSD to check whether this works correct there, too.

**Comment by RolandRosenfeld** [comment]
I just released 0.47 of lbdb (see https://www.spinnaker.de/lbdb/download/ ), which comes with a rewritten m_muttalias.sh, that uses completely rewritten sed calls, using "sed -E" (uses POSIX ERE instead of BRE before) and should be compatible with all POSIX compatible versions of sed, including FreeBSD sed.
Please try out, whether this works for you.

**Comment by hvanderheide** [comment]
Works like a charm. Thanks!

**Comment by RolandRosenfeld** [comment]
Thanks for the positive feedback!

**Pull request closed without merging**
