### PR TITLE
lbdbq: support config in XDG_CONFIG_HOME

### PR DESCRIPTION
**Pull request by tretter**

### CODE REVIEW

**Review by RolandRosenfeld — COMMENTED** [review]
Sounds like a very good idea to me (It's already on the TODO list for ages).
Two things are missing, before I release this.
- support for ldap.rc (in mutt_ldap_query)
- support for XDG_DATA_HOME to handle m_inmail address list m_fido nodelist.

It's great to have the first step done now, which makes the rest a little easier (but I'm still not sure how to handle XDG_DATA_HOME on a system, where $HOME/.lbdb already exists: place/search files in $XDG_DATA_HOME or $HOME/.lbdb or in both of them?)

**Comment by tretter** [comment]
Thanks for the review. I will have a look at the open items and finish this sometime.

**Comment by tretter** [comment]
I added the XDG_CONFIG_HOME documentation to the README and added support for the ldap.rc. As I have no experience with Perl, the added code in mutt_ldap_query.pl might not be very Perl-ish.

> I'm still not sure how to handle XDG_DATA_HOME on a system, where $HOME/.lbdb already exists: place/search files in $XDG_DATA_HOME or $HOME/.lbdb or in both of them?

I would use existing files in $HOME/.lbdb, but fall back to $XDG_DATA_HOME if the specific files are missing in $HOME/.lbdb. I guess new files should be only placed in $XDG_DATA_HOME.

**Comment by jchristgit** [comment]
Hi! Sorry to wake up this hibernating PR, but I've recently installed lbdb and I was looking for exactly this functionality. Is there a way to help out here? Outside of that I am super happy with it, thank you for this tool 🙂

**Comment by RolandRosenfeld** [comment]
Just merged

**Comment by RolandRosenfeld** [comment]
Just merged your pull request with little changes...

**Comment by RolandRosenfeld** [comment]
Now $XDG_DATA_HOME support for several files is pending...

**Comment by jchristgit** [comment]
> Just merged

Thank you so much!

> Now $XDG_DATA_HOME support for several files is pending...

Do you mean `$HOME/.lbdb/m_inmail.utf-8` from `m_inmail` and `$HOME/.lbdb/nodelist` from `m_fido`? I don't have Fido set up but I can look into adding it for `m_inmail`.

**Comment by RolandRosenfeld** [comment]
Especially the m_inmail.utf-8 file should be relocated from $HOME/.lbdb/ to $XDG_DATA_HOME/lbdb/.
The challenge here is how to handle upgrades as smooth as possible for the users.
While configuration can be read from multiple files, the m_inmail database is written by lbdb-fetchmail and read by m_inmail module.  lbdb-fetchmail comes with exactly one location compiled in where it writes the data (which can be changed via command line option), while m_inmail module database file location can be changed via environment/shell variable (but both must be in sync).
Simply changing the default database path will cause trouble for users on upgrade.
Since I have no idea how to work around this, I delayed the introduction of $XDG_DATA_HOME...

**Comment by jchristgit** [comment]
What about: if $XDG_DATA_HOME/lbdb exists, it will be used in both 
lbdb-fetchmail and m_inmail, and if not, the existing behaviour is used?

I believe that way no unexpected breakage would come in and enabling the 
new behaviour can be done with only `mkdir $XDG_DATA_HOME/lbdb`.

**Pull request closed without merging**
