### PR TITLE
m_mu: Also select addresses without a name & remove overfluous quotes

### PR DESCRIPTION
**Pull request by Melkor333**
This change would allow to search for a sole mail address from `m_mu` even when the mail address doesn't have a `Name` attribute. In that case the Mail address is set as the Name.

### CODE REVIEW

**Comment by Melkor333** [comment]
I also just saw that other sources don't put quotes around the output, while `mu cfind --format=csv ...` puts `"` around it. Therefore I added a very cheap fix to remove the quotes.

---

It's actually probably better to trash the CSV stuff and use the `mutt-ab` format, which is almost what `lbdbq` normally outputs and just remove the first line & add the `mu cfind` comment:
```
mu cfind --format mutt-ab $MU_OPTIONS "$@" | tail +2 | sed -e 's/$/\tmu cfind/'
```
(arguably bad) example:
```shell
# mu cfind --format mutt-ab github | tail +2 | sed -e 's/$/\tmu cfind/'
review_requested@noreply.github.com     Review requested                mu cfind
noreply@github.com      adfinis/effing-package-manager-docker           mu cfind
mention@noreply.github.com      Mention         mu cfind
author@noreply.github.com       Author          mu cfind
timedctl@noreply.github.com     adfinis/timedctl                mu cfind
```

**Comment by Melkor333** [comment]
I can update the file to use `--format mutt-ab`, but I'd be glad to have a feedback first if this kind of change is even appreciated or if it e.g. would break too much (in which case the change could for example be made optional)

**Comment by RolandRosenfeld** [comment]
To say the truth, I never used the mu code myself before, this is completely written by Timothy Bourke.
Following the git history, he started using format mutt-ab and switched over to csv (for "more robust handling of missing names"), so switching back to mutt-ab should be well considered...

In the meantime I started using autotest and try to create a test with some test data for every module before modifying it.
So before merging your pull request, I'd like to add a test for m_mu and to dig deeper in how mu cfind works.

So it may take a little longer before I'm able to work on your pull request...

**Comment by RolandRosenfeld** [comment]
Hi @Melkor333,

in the meantime I started a mu-test branch, which tests m_mu and expects the current output of the module.

With the mix of different address formats from my testsuite I than checked what --format=mutt-ab does in contrast to --format=csv and I agree with you that mutt-ab looks much cleaner and straight forward than the CSV stuff.

Instead of running tail -2, I tend to add a "-e 1d" as the first argument of sed, which saves one fork.
The disadvantage of mutt-ab is, that it supports entries without real name, but then uses an empty real name column.
I think about filling this column with the local part of the mail address (not the complete mail address as you did above):
```bash
        $MU cfind --format=mutt-ab $MU_OPTIONS "$@" \
            | sed -e 1d \
                  -e 's/\(\([^,@]*\)@[^,]*\)		/\1	\2	/' \
                  -e 's/$/mu cfind/'
```
What do you think, does this sound like a good idea or should we simply do `sed -e 1d -e 's/$/mu cfind/'` and live with the empty realname?

Should I add another config option (MU_HIDE_EMPTY_NAME or the like), that can hide entries without real name?

I'll have to sleep a night over this and generate new files with the changed expected output for my test afterwards.

**Comment by RolandRosenfeld** [comment]
I just released a new 0.55 switching over to --format=mutt-ab (using the local part of the mail address as name) and adding an option MU_IGNORE_MISSINGNAME (not set by default) the reverts to the old behavior (not showing entries without a name).

I hope, that this is implements all you wanted to reach with your pull request and close it.

**Comment by Melkor333** [comment]
Oh wow thanks, definitely fast response!
I was going to answer that I think this is nice but busy life.... :)

Exactly the implementation I would've wanted!

**Pull request closed without merging**
